### ISSUE TITLE
Boursobank access is broken

### ISSUE THREAD

**Issue by spougne** [rbignon/woob#5]
Hello,

The boursobank module is broken since some days.
I tried from Kresus and command line result is the same.

This is the log from Kresus.

2023-12-26 21:09:54,653:DEBUG:urllib3.connectionpool:connectionpool.py:1019:_new_conn Starting new HTTPS connection (1): api.boursobank.com:443
2023-12-26 21:09:55,087:DEBUG:urllib3.connectionpool:connectionpool.py:474:_make_request https://api.boursobank.com:443 "POST /services/api/v1.7/_user_/_5b76ab98198e2b5_/session/otp/checksms/10305 HTTP/1.1" 200 None
2023-12-26 21:09:55,101:DEBUG:woob.boursorama.browser:browsers.py:1004:internal_callback Handle https://api.boursobank.com/services/api/v1.7/_user_/_5b76ab98198e2b5_/session/otp/checksms/10305 with OtpCheckPage
2023-12-26 21:09:55,106:DEBUG:urllib3.connectionpool:connectionpool.py:1019:_new_conn Starting new HTTPS connection (1): clients.boursobank.com:443
2023-12-26 21:09:55,383:DEBUG:urllib3.connectionpool:connectionpool.py:474:_make_request https://clients.boursobank.com:443 "GET /aide/messages/dashboard?showza=0&_hinclude=1 HTTP/1.1" 302 298
2023-12-26 21:09:55,579:DEBUG:urllib3.connectionpool:connectionpool.py:474:_make_request https://clients.boursobank.com:443 "GET /securisation HTTP/1.1" 200 None
2023-12-26 21:09:55,690:DEBUG:woob.boursorama.browser:browsers.py:1004:internal_callback Handle https://clients.boursobank.com/securisation with AuthenticationPage
2023-12-26 21:09:55,742:DEBUG:urllib3.connectionpool:connectionpool.py:474:_make_request https://clients.boursobank.com:443 "GET /aide/messages/dashboard?showza=0&_hinclude=1 HTTP/1.1" 302 298
2023-12-26 21:09:55,947:DEBUG:urllib3.connectionpool:connectionpool.py:474:_make_request https://clients.boursobank.com:443 "GET /securisation HTTP/1.1" 200 None
2023-12-26 21:09:55,955:DEBUG:woob.boursorama.browser:browsers.py:1004:internal_callback Handle https://clients.boursobank.com/securisation with AuthenticationPage
2023-12-26 21:09:56,004:DEBUG:urllib3.connectionpool:connectionpool.py:474:_make_request https://clients.boursobank.com:443 "GET /dashboard/comptes-professionnels?_hinclude=1 HTTP/1.1" 302 298
2023-12-26 21:09:56,317:DEBUG:urllib3.connectionpool:connectionpool.py:474:_make_request https://clients.boursobank.com:443 "GET /securisation HTTP/1.1" 200 None
2023-12-26 21:09:56,333:DEBUG:woob.boursorama.browser:browsers.py:1004:internal_callback Handle https://clients.boursobank.com/securisation with AuthenticationPage
[2023-12-26T21:09:56.452] [INFO] providers/woob - Command returned an error code.
[2023-12-26T21:09:56.453] [INFO] providers/woob - Checking that woob is installed and can actually be called…
[2023-12-26T21:09:56.453] [INFO] providers/woob - Calling woob: command test...
[2023-12-26T21:09:56.762] [INFO] providers/woob - exited with code 0.
[2023-12-26T21:09:56.762] [INFO] providers/woob - OK: woob exited normally with non-empty JSON content.
[2023-12-26T21:09:56.762] [ERROR] providers/woob - Got error while running command "3": Unknown error: .
Traceback (most recent call last):
  File "/usr/local/share/.config/yarn/global/node_modules/kresus/build/server/providers/woob/py/main.py", line 702, in fetch
    results['values'] = self.get_accounts()
                        ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/share/.config/yarn/global/node_modules/kresus/build/server/providers/woob/py/main.py", line 552, in get_accounts
    for account in list(self.backend.iter_accounts()):
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/data/woob-data/modules/3.6/woob_modules/boursorama/module.py", line 69, in iter_accounts
    return self.browser.get_accounts_list()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/woob/browser/retry.py", line 75, in wrapper
    ret = cb()
          ^^^^
  File "/usr/local/lib/python3.11/dist-packages/woob/browser/retry.py", line 71, in <lambda>
    cb = lambda: func(browser, *args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/woob/browser/browsers.py", line 1121, in inner
    return func(browser, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/data/woob-data/modules/3.6/woob_modules/boursorama/browser.py", line 561, in get_accounts_list
    assert self.no_account.is_here()
AssertionError

[2023-12-26T21:09:56.762] [ERROR] providers/woob - 	(error code: GENERIC_EXCEPTION)
[2023-12-26T21:09:56.769] [ERROR] controllers/accesses - The access process creation failed, cleaning up...
[2023-12-26T21:09:56.769] [INFO] controllers/accesses - 	deleting access...
[2023-12-26T21:09:56.771] [ERROR] helpers - when creating a bank access: Unknown error: .
Traceback (most recent call last):
  File "/usr/local/share/.config/yarn/global/node_modules/kresus/build/server/providers/woob/py/main.py", line 702, in fetch
    results['values'] = self.get_accounts()
                        ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/share/.config/yarn/global/node_modules/kresus/build/server/providers/woob/py/main.py", line 552, in get_accounts
    for account in list(self.backend.iter_accounts()):
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/data/woob-data/modules/3.6/woob_modules/boursorama/module.py", line 69, in iter_accounts
    return self.browser.get_accounts_list()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/woob/browser/retry.py", line 75, in wrapper
    ret = cb()
          ^^^^
  File "/usr/local/lib/python3.11/dist-packages/woob/browser/retry.py", line 71, in <lambda>
    cb = lambda: func(browser, *args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/woob/browser/browsers.py", line 1121, in inner
    return func(browser, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/data/woob-data/modules/3.6/woob_modules/boursorama/browser.py", line 561, in get_accounts_list
    assert self.no_account.is_here()
AssertionError

[2023-12-26T21:09:56.772] [INFO] helpers - Error
    at new KError (/usr/local/share/.config/yarn/global/node_modules/kresus/build/server/helpers.js:62:22)
    at callWoob (/usr/local/share/.config/yarn/global/node_modules/kresus/build/server/providers/woob/index.js:234:15)
    at async _fetchHelper (/usr/local/share/.config/yarn/global/node_modules/kresus/build/server/providers/woob/index.js:291:16)
    at async Object.fetchAccounts (/usr/local/share/.config/yarn/global/node_modules/kresus/build/server/providers/woob/index.js:305:12)
    at async pollAccounts (/usr/local/share/.config/yarn/global/node_modules/kresus/build/server/lib/accounts-manager.js:96:34)
    at async AccountManager.syncAccounts (/usr/local/share/.config/yarn/global/node_modules/kresus/build/server/lib/accounts-manager.js:278:24)
    at async createAndRetrieveData (/usr/local/share/.config/yarn/global/node_modules/kresus/build/server/controllers/accesses.js:119:33)
    at async create (/usr/local/share/.config/yarn/global/node_modules/kresus/build/server/controllers/accesses.js:184:22)
[2023-12-26T21:09:56.773] [ERROR] HTTP - POST /api/accesses - 500 (2469 ms)

**Comment by tykayn** [comment]
i second this issue, it is still broken since 2023. can anyone have a look please?

**Comment by cchazalet** [comment]
This issue is still active, can anyone have a look please ?
